{% set name = "scikit-mol" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit_mol-{{ version }}.tar.gz
  sha256: da32327092e64d0be85774c0ea19457f7a08fc02a7a4beb8c895183470302c69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=64
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - rdkit
    - numpy
    - pandas
    - scikit-learn
    - packaging

test:
  imports:
    - scikit_mol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/EBjerrum/scikit-mol
  summary: scikit-learn classes for molecule transformation
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
