{% set name = "scikit-mol" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scikit_mol-{{ version }}.tar.gz
  sha256: 1483b380b1bd9bce3195af38eb283fb2d3ee5876902e3d086046d7b537dca4be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=6.2
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - rdkit
    - numpy
    - pandas
    - scikit-learn
    - packaging

test:
  imports:
    - scikit_mol
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/EBjerrum/scikit-mol
  summary: scikit-learn classes for molecule transformation
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
    - EBjerrum
